services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG}
    # container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    environment:
      - 'WEBUI_NAME=NeiroLawyer'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
      - 'DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE}'
      - 'DATABASE_POOL_MAX_OVERFLOW=${DATABASE_POOL_MAX_OVERFLOW}'
      - 'DATABASE_POOL_TIMEOUT=${DATABASE_POOL_TIMEOUT}'
      - 'STORAGE_PROVIDER=${STORAGE_PROVIDER}'
      - 'S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}'
      - 'S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}'
      - 'S3_ENDPOINT_URL=${S3_ENDPOINT_URL}'
      - 'S3_REGION_NAME=${S3_REGION_NAME}'
      - 'S3_BUCKET_NAME=${S3_BUCKET_NAME}'
      - 'OPENAI_LOG_LEVEL=${OPENAI_LOG_LEVEL}'
      - 'GLOBAL_LOG_LEVEL=${GLOBAL_LOG_LEVEL}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  postgres_data: {}
  open-webui: {}
